# TODO: change here
name: flutter_template
description: flutter template with some useful packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.0 # Add this line

  # State Management
  flutter_riverpod:
  hooks_riverpod:
  flutter_hooks:
  
  # Hive: DB
  hive:
  hive_flutter: 

  # Login
  google_sign_in:
  
  # managing app informations
  flutter_launcher_icons:
  package_info_plus: 

  # assets
  cupertino_icons: ^1.0.2

  # code generations
  freezed_annotation:
  json_annotation: 

  # ui
  flutter_dialogs: 

  # others
  go_router: ^14.8.1 
  flutter_pdfview: ^1.4.0
  syncfusion_flutter_pdfviewer: ^29.1.37
  pdf: ^3.11.3
  printing: ^5.14.2
  pdfx: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # data handling
  json_serializable: 

  # lints
  flutter_lints:
  riverpod_lint: 

  # code generation
  build_runner: 
  hive_generator: 
  freezed:



flutter:
  uses-material-design: true
  assets:
   - assets/icons/eraser.png

  fonts:
    - family: IBMPlexSansKR
      fonts:
        - asset: assets/fonts/IBMPlexSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansKR-Thin.ttf
          weight: 100